
package br.edu.ifsul.cc.lpoo.cs.gui.jogador.designer;

/**
 *
 * @author telmo
 */
public class JPanelDJogadorListagem extends javax.swing.JPanel {

    /**
     * Creates new form JPanelDJogadorListagem
     */
    
    private JPanelDJogador pnlJogador;
    
    
    public JPanelDJogadorListagem() {
        initComponents();
    }
    
    public JPanelDJogadorListagem(JPanelDJogador pnlJogador) {
        this.pnlJogador = pnlJogador;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFiltro = new javax.swing.JLabel();
        txfFiltro = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        lblFiltro.setText("Filtrar por Nickname:");
        jPanel1.add(lblFiltro);

        txfFiltro.setColumns(10);
        jPanel1.add(txfFiltro);

        btnFiltrar.setText("Filtrar");
        jPanel1.add(btnFiltrar);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jButton2.setText("Novo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        btnEditar.setText("Editar");
        jPanel2.add(btnEditar);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nickname", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


        
        
        
        
        
        




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JTextField txfFiltro;
    // End of variables declaration//GEN-END:variables
}
