
package br.edu.ifsul.cc.lpoo.cs.gui.jogador.designer;

import br.edu.ifsul.cc.lpoo.cs.Controle;
import java.awt.CardLayout;
import java.awt.LayoutManager;

/**
 *
 * @author telmo
 */
public class JPanelDJogador extends javax.swing.JPanel {

 
    private JPanelDJogadorListagem listagem;
    
    private Controle controle;
    
    private CardLayout cl ;
    
    
    public JPanelDJogador(Controle controle) {
        
        this.controle = controle;
        
        
        initComponents();
        
        listagem = new JPanelDJogadorListagem(this);
        
        
        this.add(listagem, "listagem");
        
        cl = (CardLayout) this.getLayout();
        
       
    }
    
        
    public void showTela(String nomeTela){
         
         cl.show(this, nomeTela);
         
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
